{% set name = "napari-affinities" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/napari-affinities-{{ version }}.tar.gz
  sha256: 0031575f74f5d866b15d21368f7e3ee7dc921c362d79103bcc9caa73593f9eca

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }},<3.10a0
    - pytorch >=1.3.1
    - numpy
    - zarr
    - magicgui
    - bioimageio.core
    - gunpowder
    - affogato
    - matplotlib-base
    - lsds

test:
  imports:
    - napari_affinities
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pattonw/napari-affinities
  summary: A plugin for creating, visualizing, and processing affinities
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - pattonw
